### ISSUE TITLE
Refarctor Mod bus XML parser

### ISSUE THREAD

**Issue by ignacio-penas** [nuvlaedge/nuvlaedge#121]
The goal is to refactor the "parse_modbus_peripherarls" function in order to reduce complexity and  to make it more testable and readable.

Also, it would be optimal to use ElementTree xml library instead of xmltodict as done in nuvlaedge/security/Security xml parsing.  

By default, the xml output of the modbus nmap scan can be found in /tmp/nmap_scan.xml after the scan is ran once. 
To test the Modbus, in parallel to the nuvlaedge we can run a dummy modbus server like: 
`docker run -d --rm -p 502:5020 oitc/modbus-server:latest`

**Comment by konstan** [comment]
@amitbhanja Location of `parse_modbus_peripherarls` https://github.com/nuvlaedge/nuvlaedge/blob/main/nuvlaedge/peripherals/modbus/__init__.py#L70

**Comment by amitbhanja** [comment]
Moving to Done as a demo is done.
