### ISSUE TITLE
add test VPN server to preprod.nuvla.io

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvlaedge/nuvlaedge#28]
Find a way to have a testbed for VPN-related workflows (ie. testing development features on a NuvlaBox, that required VPN)

**Comment by cjdcordeiro** [comment]
@schaubl can you help me test this?

**Comment by schaubl** [comment]
@cjdcordeiro yes we can have a look

**Comment by schaubl** [comment]
There is now a preprod VPN configured for swarm.nuvla.io

**Comment by schaubl** [comment]
TDB on preprod.nuvla.io
