### ISSUE TITLE
which k8s implementations require additional tools for multi-clustering support and what those tools are

### ISSUE THREAD

**Issue by konstan** [nuvlaedge/nuvlaedge#38]

**Comment by giovannibianco** [comment]
k8s does not support multi-cluster out of the box.
Requires any one of kube-edge, submariner or skupper to achieve.
Caveat: https://docs.k3s.io/networking#multicluster-cidr-experimental

k3s claims to support multi-cluster... but does this with submariner.

microk8s claims to support out of the box see: https://microk8s.io/docs/clustering
