### ISSUE TITLE
NE on K8s: validate peripheral discovery works on K8s

### ISSUE THREAD

**Issue by konstan** [nuvlaedge/nuvlaedge#81]
Validate peripheral discovery works. Collect found issues.

- [x] bluetooth
- [x] gpu
- [x] modbus
- [x] network
- [x] usb

**Comment by schaubl** [comment]
`gpu`, `network`, `usb` have been tested and work properly.

**Comment by giovannibianco** [comment]
Working on the bluetooth peripheral discovery... It is working...
* Home Raspberry pi
* `Linux sonal-raspberrypi 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux`
* Bluetooth enabled and scanned.
* Used my old Blackberry Q20 as the connecting device ?(hopefully not BLE?)
* Install with bluetooth enabled and can see the device
* See attached screenshot from nuvla.io

![Screenshot 2023-08-14 at 17 54 46](https://github.com/nuvlaedge/nuvlaedge/assets/3775436/156e293e-789b-4bec-abb9-2a1aaebd9df6)

**Comment by giovannibianco** [comment]
OK... so the `modbus` becomes a bit clearer now...

Assuming that we have `modbus` server running on the `kubernetes` host (VM, raspberry pi etc etc)
This is mapped to a known port (502)
The code inside the modbus peripheral manager uses:
'''
nmap --script modbus-discover.nse --script-args='modbus-discover.aggressive=true' -p- hostname -T4 -oX xml_file > /dev/null"
'''

Inside the container, the `hostname` is found as the default gateway IP.
This is fine for docker-based deployments as this will be the host IP where docker is running.

For kubernetes this causes a problem as the default gateway for a pod (as the peripheral manager is run) is the CNI gateway, not the IP of the local host.

Therefore, in the kubernetes case, the `nmap` scan will not find a `modbus` on the host.

**Comment by giovannibianco** [comment]
The modbus can now be detected on a NuvlaEdge host.

**Comment by konstan** [comment]
@giovannibianco New way of modbus discovery [was implemented](https://github.com/nuvlaedge/nuvlaedge/issues/121). Validate it works with K8s.

**Comment by giovannibianco** [comment]
Modbus  detection on both Kubermetes and Docker is fixed. See the attached images for each:
![Screenshot 2023-10-12 at 11 04 27](https://github.com/nuvlaedge/nuvlaedge/assets/3775436/748fb16f-e1d5-46d0-abdd-24a4fa442e82)
![Screenshot 2023-10-12 at 11 39 42](https://github.com/nuvlaedge/nuvlaedge/assets/3775436/d1d5fbae-1ecc-4cbd-8547-eceaf5bc8511)

**Comment by konstan** [comment]
Moved back to In Progress. This PR needs review https://github.com/nuvlaedge/nuvlaedge/pull/116

**Comment by konstan** [comment]
Each of the peripheral discoveries was demoed. The last one was modbus. Closing.
